### ISSUE TITLE
Docker Container isn't starting

### ISSUE THREAD

**Issue by sockpapi** [parcelvoy/platform#125]
Here are the logs: 

`ERROR: for api  Container "4b6347da86c0" is unhealthy.
ERROR: Encountered errors while bringing up the project.
[ec2-user@ip-172-31-91-197 platform]$ docker logs 4b6347da86c
2023-04-13 14:42:01+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.27-1debian10 started.
2023-04-13 14:42:01+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2023-04-13 14:42:01+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.27-1debian10 started.
2023-04-13T14:42:01.750028Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.27) starting as process 1
2023-04-13T14:42:01.761481Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2023-04-13T14:42:02.018619Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2023-04-13T14:42:02.214023Z 0 [Warning] [MY-013746] [Server] A deprecated TLS version TLSv1 is enabled for channel mysql_main
2023-04-13T14:42:02.214060Z 0 [Warning] [MY-013746] [Server] A deprecated TLS version TLSv1.1 is enabled for channel mysql_main
2023-04-13T14:42:02.214947Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2023-04-13T14:42:02.214995Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2023-04-13T14:42:02.217367Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2023-04-13T14:42:02.240228Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
2023-04-13T14:42:02.240441Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.27'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.`

I have tried everything - even Gpt4 can't figure it out 😂

**Comment by sockpapi** [comment]
I got it working by making changes to the docker-compose.yml. Here is my version 
`version: '3'
services:
  mysql:
    image: mysql:8.0.27
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_AUTHENTICATION_PLUGIN=caching_sha2_password
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      retries: 10
      timeout: 10s
      start_period: 30s
  redis:
    image: redis
    expose:
      - "6379"
    restart: always
    volumes:
      - redis_data:/data
  api:
    image: 'ghcr.io/parcelvoy/api:latest'
    restart: always
    ports:
      - 3001:3001
    links:
      - mysql:mysql
    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_started
    environment:
      NODE_ENV: ${NODE_ENV}
      BASE_URL: ${BASE_URL}
      RUNNER: 'api'
      APP_SECRET: ${APP_SECRET}
      PORT: 3001
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: mysql
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      STORAGE_DRIVER: ${STORAGE_DRIVER}
      STORAGE_BASE_URL: ${STORAGE_BASE_URL}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      QUEUE_DRIVER: ${QUEUE_DRIVER}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      AWS_SQS_QUEUE_URL: ${AWS_SQS_QUEUE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AUTH_DRIVER: ${AUTH_DRIVER}
      AUTH_BASIC_EMAIL: ${AUTH_BASIC_EMAIL}
      AUTH_BASIC_PASSWORD: ${AUTH_BASIC_PASSWORD}
      AUTH_SAML_CALLBACK_URL: ${AUTH_SAML_CALLBACK_URL}
      AUTH_SAML_ENTRY_POINT_URL: ${AUTH_SAML_ENTRY_POINT_URL}
      AUTH_SAML_ISSUER: ${AUTH_SAML_ISSUER}
      AUTH_SAML_CERT: ${AUTH_SAML_CERT}
      AUTH_SAML_IS_AUTHN_SIGNED: ${AUTH_SAML_IS_AUTHN_SIGNED}`

**Comment by sockpapi** [comment]
updated docker-compose: mysql:
  image: mysql:8.0.27
  platform: linux/x86_64
  environment:
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    - MYSQL_AUTHENTICATION_PLUGIN=caching_sha2_password
  expose:
    - 3306
  volumes:
    - mysql_data:/var/lib/mysql
  restart: unless-stopped
  healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
    interval: 10s
    timeout: 10s
    retries: 5
    start_period: 30s

**Comment by sockpapi** [comment]
Sorry for all of the messages, I am very excited to get this running :)

**Comment by pushchris** [comment]
@sockpapi can you provide some more information about the machine you are trying to run this on?

**Comment by sockpapi** [comment]
Hey @pushchris , Amazon Linux 2 - t2.large. I switched to using a RDS mySql. That seems to solve my issue. But now I can't connect to the UI. I am trying http://{public_ip}:3000    , I tried switching BASE_URL and STORAGE_BASE_URL to have my IP in it, no luck. Btw, I LOVE this product you're building. I have been looking for something like this for a long time

**Comment by pushchris** [comment]
Appreciate the kind words! Everything is very much in alpha and subject to break but hoping to add lots of functionality quickly.

What do you have `UI_PORT` set to? That will be the port you use to access the platform on. `BASE_URL` is just used internally for creating things like unsubscribe URLs, etc and `STORAGE_BASE_URL` is used for image URLs (great use case would be if you are using a CDN for example to re-write the paths of images)

**Comment by sockpapi** [comment]
UI PORT = 3000

**Comment by sockpapi** [comment]
We should do a e-meeting soon! my email is todd@threadstudio.com

**Comment by pushchris** [comment]
Ok, there are definitely some issues in the documentation. I tried going through the quick start step by step on a fresh instance and it's not working for me either. Will look through and update. One other thing to check out (and that appears to be missing in the example .env file) is the `API_BASE_URL` key which should default to `API_BASE_URL=https://localhost:3000/api`. You can split the API and UI images onto separate servers if you want, but they need to be on the same domain so the cookies work. Try setting that key and seeing if it loads. Does the UI piece completely not load at all or does it show an error message?

**Comment by sockpapi** [comment]
I did see the docs were inspired by airbyte 😂 Let me give that a try now

**Comment by sockpapi** [comment]
wouldn't the API base url be http not https?

**Comment by sockpapi** [comment]
Just emailed you my server details. Getting a ERR_CONNECTION_TIMED_OUT when I go to the UI URL.

**Comment by pushchris** [comment]
Glad we were able to get everything running. I've made a number of changes to the documentation and compose file that should hopefully make it less confusing for others starting off. If you run into anything else please dont hesitate to reach out again or open another issue.
