### ISSUE TITLE
Deplyment on ec2 instance t3.medium failing

### ISSUE THREAD

**Issue by chandantiwari** [parcelvoy/platform#211]
I followed the instructions and tried to deploy on t3.medium Amz ec2 instance and getting the following error - 

<img width="1101" alt="Screenshot 2023-06-29 at 12 58 21" src="https://github.com/parcelvoy/platform/assets/4123626/034c57c7-e52c-48f6-999c-3d88d0dff0ca">

What am I doing wrong?

**Comment by pushchris** [comment]
Can you please post the full logs from the docker compose boot? If you are running in detached mode, you can get them by running `docker-compose logs` otherwise just don't run in detached mode (no `-d`) to see the logs as it starts.

**Comment by chandantiwari** [comment]
Thanks for the prompt reply. I was able to get them to work creating a new instance.
However, when I call API using POSTMAN with a public bearer key, it says 405 Not Allowed. 
<img width="883" alt="Screenshot 2023-07-04 at 15 58 46" src="https://github.com/parcelvoy/platform/assets/4123626/6f71b85d-526f-4d7d-8081-ccd6ee85fa18">

**Comment by chandantiwari** [comment]
Thanks for your prompt reply. I was able to get that working. 
However, when using the API through Postman, I am getting an error. Attaching both postman and log of the container for API service. 
<img width="648" alt="Screenshot 2023-07-04 at 16 21 41" src="https://github.com/parcelvoy/platform/assets/4123626/0468e576-e032-4bc5-9c8e-977c08491d50">
<img width="815" alt="Screenshot 2023-07-04 at 16 22 02" src="https://github.com/parcelvoy/platform/assets/4123626/77e7b261-13d0-4a55-a156-e061607c9cef">

**Comment by chandantiwari** [comment]
Tried both 3000 as well as 3001 .

**Comment by pushchris** [comment]
Ok great, please reach out if you have any further issues.
