### ISSUE TITLE
Adding SMTP Account Error 

### ISSUE THREAD

**Issue by sockpapi** [parcelvoy/platform#213]
When I attempt to add a SMTP account in the UI, I get this error: `Error
Must be number`  . Here is the my payload request: {
  "host": "email.hostname.io",
  "port": "465",
  "secure": true,
  "auth": {
    "user": "my email address",
    "pass": "password"
  }
}

**Comment by sockpapi** [comment]
I got it working by running the HTTP request locally and changing to the port to an INT

**Comment by pushchris** [comment]
Thanks for the report @sockpapi, fixed in the v0.8.3 release
