### ISSUE TITLE
Unable to setup a campaign with a local webhook channel

### ISSUE THREAD

**Issue by Ebaneck** [parcelvoy/platform#219]
Hello,
I have a local setup of parcelvoy with docker-compose.

I have gone ahead to setup a [webhook integration](https://webhook.site/#!/b04a3e6f-bea8-4e05-9001-76938b87c3d3)  together with a simple campaign and I am unable
to get the webhook working correctly. In the logs, i see the following:

```
worker_1  |     error: {}
worker_1  | [1688592420268] ERROR (9 on 6e41aeabb571): queue:job:errored
worker_1  |     stacktrace: "TypeError: Cannot convert undefined or null to object\n    at Function.keys (<anonymous>)\n    at WebhookChannel.send (/usr/src/app/providers/webhook/WebhookChannel.js:22:29)\n    at handler (/usr/src/app/providers/webhook/WebhookJob.js:29:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Queue.dequeue (/usr/src/app/queue/Queue.js:36:9)\n    at async worker.bullmq_1.Worker.connection [as processFn] (/usr/src/app/queue/RedisQueueProvider.js:62:13)\n    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:346:28)\n    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:520:24)"
worker_1  |     job: {
worker_1  |       "name": "webhook",
worker_1  |       "data": {
worker_1  |         "campaign_id": 10,
worker_1  |         "user_id": 20,
worker_1  |         "send_id": 39
worker_1  |       },
worker_1  |       "options": {
worker_1  |         "delay": 0,
worker_1  |         "attempts": 3
worker_1  |       }
worker_1  |     }
worker_1  |     error: {}
mysql_1   | mbind: Operation not permitted
```

Could you please help shed some light on this? 
Thanks

<img width="1437" alt="Screenshot 2023-07-05 at 23 37 59" src="https://github.com/parcelvoy/platform/assets/10956602/828c080d-4fb8-43fe-89df-d4b2f7431e34">

**Comment by pushchris** [comment]
Thanks for the report @Ebaneck! It looks like when headers are undefined the handlebars compiler freaks out a bit. A fix for this has been merged and will be available in the next release

**Comment by Ebaneck** [comment]
Thanks alot @pushchris for looking at this in such a short notice.
By the way, do you happen to know when the next release is scheduled?

**Comment by Ebaneck** [comment]
Hello @pushchris 
I still couldn't get the webhook endpoints up and running for a sample campaign.
Even when I try-out the preview (Test Webhook) button, I get the following:

```
ui_1      | 172.31.0.1 - - [26/Dec/2023:00:56:30 +0000] "POST /api/admin/projects/1/templates/2/preview HTTP/1.1" 400 65 "http://localhost:3000/projects/1/campaigns/2/preview" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "-"
api_1     | 
api_1     |   TypeError [ERR_INVALID_URL]: Invalid URL
api_1     |       at new NodeError (node:internal/errors:405:5)
api_1     |       at new URL (node:internal/url:676:13)
api_1     |       at paramsToEncodedLink (/usr/src/app/build/render/LinkService.js:18:17)
api_1     |       at unsubscribeEmailLink (/usr/src/app/build/subscriptions/SubscriptionService.js:153:50)
api_1     |       at exports.default (/usr/src/app/build/render/index.js:78:77)
api_1     |       at WebhookTemplate.compile (/usr/src/app/build/render/Template.js:207:41)
api_1     |       at /usr/src/app/build/render/TemplateController.js:263:25
api_1     |       at dispatch (/usr/src/app/node_modules/koa-compose/index.js:42:32)
api_1     |       at /usr/src/app/build/render/TemplateController.js:196:18
api_1     |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
api_1     |       at async serve (/usr/src/app/node_modules/koa-static/index.js:59:5)
api_1     |       at async cors (/usr/src/app/node_modules/@koa/cors/index.js:110:16)
api_1     |       at async /usr/src/app/build/api.js:48:17
api_1     | 

```

**Comment by pushchris** [comment]
@Ebaneck could you post some details about the webhook you have created? An example URL and body that fail would be awesome. It particularly looks like the error could be URL related based on what you posted above. Thanks!

**Comment by pushchris** [comment]
Actually, it's most likely something to do with your ENV variable `BASE_URL`. Do you have that set to something specific? Or is it using the default value?

**Comment by Ebaneck** [comment]
For ENV variables, here is what I have
```
BASE_URL=/
UI_PORT=3000
```

**Comment by Ebaneck** [comment]
> @Ebaneck could you post some details about the webhook you have created? An example URL and body that fail would be awesome. It particularly looks like the error could be URL related based on what you posted above. Thanks!

Regarding my webhook settings, I using a sample generated from https://webhook.site/
Here is a screenshot of my current setup

<img width="1430" alt="Screenshot 2023-12-26 at 11 49 11" src="https://github.com/parcelvoy/platform/assets/10956602/b0b683b3-21c1-465b-b280-ec9ffa0bf317">

**Comment by pushchris** [comment]
So `BASE_URL` has to be an absolute URL since it is used for links and references into the platform (ie the URL that users get in emails to unsubscribe, click tracking, etc). In the latest version released yesterday I added a warning when this is misconfigured to hopefully prevent others from running into it. If you are just running everything locally you can set it to `http://localhost:3000` or remove that variable completely. If you have a domain or IP from a server, set it to that. Let me know if this resolves it for you!

**Comment by pushchris** [comment]
Glad to hear it! Appreciate the reach out, hopefully this will help folks in the future as well!
