### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by 7figurefortune** [parcelvoy/platform#251]
Hello im having trouble installing the code...ive had my developer look at it as well. We are getting errors. Can you help me?

**Comment by pushchris** [comment]
@7figurefortune can you please post any relevant information or context you have? Unfortunately there is nothing to go by here. Some things that could be helpful to start:
- What are you trying to install?
- Where are you deploying the containers? (what OS, etc)

Screenshots would also be helpful

**Comment by pushchris** [comment]
@7figurefortune unless you provide an actual error message or something concrete to work off of it's impossible to provide any guidance. Please provide the actual error you are receiving as well as details as to where you are trying to run Parcelvoy from.
