### ISSUE TITLE
Regarding LICENSE

### ISSUE THREAD

**Issue by mrfambo** [parcelvoy/platform#271]
Let me explain my intention of use and seek your advice regarding the current LICENSE restrictions:

I am building a campaign platform who has its own email sending algorithm to avoid emails going into the Spam. The algorithm revolves around sending emails at variable times and variable intervals.

I am using your repository as a base start (if you allow) and build the email sending algorithm on top of it. Starting from scratch would take time, and building the UI takes hectic efforts.

Is it possible that i contribute back to you in your features and you allow the commercial use of this initial code-base? Some of the features could be helpful for you too like CSV uploads of contacts, SendGrid integration, Azure AD integration. Any thoughts?

**Comment by pushchris** [comment]
@mrfambo, apologies for the delay, we've been hard at work on a pretty major release. Regarding your question:
- If you are just using the UI components, that would not run afoul of the license as you are not providing any features included in the library to your user base
- However, if you will also be utilizing all of the backend framework that we have built to handle the orchestration of message sending, that would constitute using the library in a hosted fashion to provide your users with a substantial set of the functionality of this library and not be permissible.

Hopefully that helps shed some light, would definitely welcome any and all contributions!
