### ISSUE TITLE
API missing important endpoints

### ISSUE THREAD

**Issue by andreieuganox** [parcelvoy/platform#315]
Dear Team,

We have started to look into your product and find it quite helpful.

However, some critical parts still need to be there, which makes it impossible to use for Production.

1. Any data must have the possibility to be deleted. It especially important for PII data. Legally, any user can request the deletion of data (GDPR right to be forgotten, for example). 
With that said, both API and UI should have the Client deletion.
Mainly, it is essential on the API level, as any mistake, for example, a wrongly created record, is currently impossible to delete.

Therefore, the `DELETE client/:id` endpoint is suggested to be implemented. P.S. Delete Job already exists.

2. API does not currently allow overwriting the data partially. Suggest that `POST /client/identify` endpoint should in fact, act as Create, as it is implied according to the REST and the endpoint name. A new endpoint is needed to `PATCH /client/:id` to update the full or partial data of the Client.

3. API is inconsistent. Examples:
a. `/client` endpoints are in fact representing the User. In fact, the internal API uses the User as the entity. 
b. `POST /client/identify` is a strange name. It is not clear what Identify actually means. It would be best to use the REST approach when working with Entities. Aka `POST /client`, `GET /client/:id`, `PATCH /client/:id`

**Comment by pushchris** [comment]
@andreieuganox there are ultimately two sets of APIs, one for administration and one for ingestion. The client API's that you are referencing as only for ingestion of data from the end user and do not allow for any destructive actions. We are working on adding better documentation for the admin set of APIs but for the use case you are describing you would:
- Generate a secret API key with at least editor permissions
- On your own server create an API to allow for deleting an account
- Call `DELETE /api/admin/projects/{PROJECT_ID}/users/{ID_TO_DELETE}` with the header `Authentication` set to `BEARER {SECRET_API_KEY}` from said API

Additionally I have just added UI inside of the admin UI to delete a user.

We will look into API consistency in the future, appreciate the suggestions.

**Comment by pushchris** [comment]
Re-addessing your third point after some internal discussion. I believe you are interpreting `client` as an endpoint when in reality it's a namespace to house the endpoints for the client API. There are three total sets of APIs: `client`, `public` and `admin` each with their own routes. The `client` namespace doesn't just handle the identification of users but also storing of events, aliasing users to new IDs, registering devices, etc.

Appreciate you reaching out about this issue, going to close this one as the core has been addressed but please feel free to reach out if you have any further issues in the future!

**Comment by andreieuganox** [comment]
Thank you for your reply! Unfortunately did not get any notifications earlier, so just spotted it....

Few comments though.

> Call DELETE /api/admin/projects/{PROJECT_ID}/users/{ID_TO_DELETE} with the header Authentication set to BEARER {SECRET_API_KEY} from said API

Admin API seems to be in fact UI API, and it makes sense when used only by UI. However, it is absolutely inefficient when you try to use it S2S. Your example above, as an example: `ID_TO_DELETE` is an internal Parcelvoy ID. So, to fetch it, I need to first search Users within the Project by External ID and then make another API call to Delete the user... You get the idea.

Just saying, that the Server (S2S) is also the `client`.. alternatively, `admin` needs to be thought through from the perspective of it being used by the server...

Just thoughts!

**Comment by pushchris** [comment]
@andreieuganox there is another deletion endpoint that is more geared towards S2S uses like you described: 
`DELETE /api/admin/projects/{PROJECT_ID}/users?user_id={EXTERNAL_ID}` it will also accept multiple IDs (just keep setting the query parameter) if you need to bulk delete.
