### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by andreieuganox** [parcelvoy/platform#316]
Please, can you clarify what is the format of the date expected in the filters. Nothing works...

<img width="1791" alt="Screenshot 2023-12-17 at 21 37 46" src="https://github.com/parcelvoy/platform/assets/29180292/2623f570-8633-4e8e-bcd2-9a8f45251c1e">

**Comment by pushchris** [comment]
@andreieuganox looks like the issue you are experiencing is actually related to a different bug. A fix has been merged and will be out in the next release. Any date that can be parsed by Node is supported (including the example you provided).
