### ISSUE TITLE
Specs on data import missing

### ISSUE THREAD

**Issue by andreieuganox** [parcelvoy/platform#317]
Can you please clarify the format expected for the Static list data import? Below is the example that fails with no helpful information provided in the error. It would be beneficial to have an example in UI. I am unclear, for example, how the custom metadata should look in CSV...?

[MarketingEmails.csv](https://github.com/parcelvoy/platform/files/13697697/MarketingEmails.csv)

**Comment by pushchris** [comment]
There is a fix merged for the list you provided. Have additionally added some documentation on what fields are available to the lists page: https://docs.parcelvoy.com/how-to/lists
