### ISSUE TITLE
Events are not consumed by the Journey

### ISSUE THREAD

**Issue by andreieuganox** [parcelvoy/platform#336]
Hi,

Here is the basic Journey setup:

<img width="2049" alt="Screenshot 2024-01-04 at 18 41 27" src="https://github.com/parcelvoy/platform/assets/29180292/fe172b58-16f7-4bcc-a239-7ccdbfa0404f">

After that:
```
curl -X "POST" "https://XXXX.com/api/client/events" \
     -H 'Authorization: Bearer ZZZZZ' \
     -H 'Accept: application/json' \
     -H 'Content-Type: application/json' \
     -d $'[
  {
    "name": "user_created",
    "external_id": "06ca2362-7950-4a2a-9a3d-142ea6bd626c"
  }
]'
```

And nothing happens - the Journey is not triggered... This event is, however, visible on the User:
<img width="1798" alt="Screenshot 2024-01-04 at 18 43 46" src="https://github.com/parcelvoy/platform/assets/29180292/5a4253c0-a41b-4cfc-9031-cf7f229519bf">

There are errors in the logs either.

**Comment by andreieuganox** [comment]
Any ideas? Maybe you can suggest the steps to debug, as currently there are 0 logs or errors...?

**Comment by pushchris** [comment]
@andreieuganox were you checking out the master branch and running it from source per chance? It looks like a previous commit regressed some journey related processes. As far as I can tell this did not affect any releases so none of the docker images were affected but want to confirm. Regardless both the master branch and the latest tag should be up to date now.

**Comment by andreieuganox** [comment]
Running from docker image, latest Release (1.1.15 if not mistaken, sorry have no laptop now)
Can roll it back one version and check what happens. Can do in around 3 hours, will report back when tested.
