### ISSUE TITLE
Feat request: Allow non-AWS S3 buckets 

### ISSUE THREAD

**Issue by andreieuganox** [parcelvoy/platform#337]
Two small amends to ask for:

1. Please extend the config in order to be able to use S3 buckets from other providers. 
At the moment, the domain can not be changed. Allowing to do so - solves the issue. 

Example of AWS SDK usage for DigitalOcean:
```
const s3Client = new S3Client({
    forcePathStyle: false, // Configures to use subdomain/virtual calling format.
    endpoint: "https://ams3.digitaloceanspaces.com", // ams3 is used in this case, for AWS it is not needed
    region: "us-east-1", // same as on AWS
    credentials: {
      accessKeyId: 'XXX',
      secretAccessKey: 'XXXX'
    }
  });
```

2. Please add some form of image base URL. You upload to the S3 bucket (on AWS or outside), but it can be served via CDN or via a custom domain. Otherwise, it can not be served via CDN at all, that is quite important for emails.

**Comment by pushchris** [comment]
Thanks for the request! Use of a CDN is already supported by setting the `STORAGE_BASE_URL` environment variable. I've started the initial work on supporting other S3-compatible providers and linked it to this issue. It should go out in the next release.

**Comment by andreieuganox** [comment]
Thank you very much! AWS is not the easiest-fastest option for spinning one service...guess it will be used by many clients of yours;)

**Comment by andreieuganox** [comment]
I saw the PR, but there are a few more amends to that.

docker-compose needs to pass the new params to the container

> STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}
    STORAGE_S3_FORCE_PATH_STYLE: ${STORAGE_S3_FORCE_PATH_STYLE}
      
apps/platform/src/storage/S3StorageProvider.ts after line 38 needs to be amended in order to make files public (as they go in emails, they need to be public)
> ACL: 'public-read'

**Comment by pushchris** [comment]
The Docker compose file has been updated. As for permissions, the platform should not be responsible for those, the end user should make sure policies for their bucket are setup according to their use case. It is not guaranteed that the end user will want those files public. For example if you have a CDN in front of the bucket, you most likely don't want the files public but rather only accessibility by the CDN, etc etc.

**Comment by pushchris** [comment]
Closing this for now, please reach out if you have any additional problems/ideas/concerns moving forward!
