### ISSUE TITLE
Build and run local

### ISSUE THREAD

**Issue by VyVu** [parcelvoy/platform#342]
hi guy, I build and run on my computer. When I login it appear error :
error: {
      "status": "error",
      "error": "Authorization error.",
      "code": 1000
    }
<img width="954" alt="image" src="https://github.com/parcelvoy/platform/assets/7249359/733d7dd1-3d1d-4ff0-bd03-dae653dcb91c">

please help me.
thanks a lot

**Comment by pushchris** [comment]
@VyVu what authentication method are you using? That error looks normal for the UI trying to access and API while it is not authenticated. Will need more information about the context of the error to provide any assistance.

**Comment by VyVu** [comment]
i'm using basic authentication method.

**Comment by pushchris** [comment]
That error is standard when trying to access the UI before you are authenticated. It's related to trying to fetch the users profile and isn't related to an authentication request itself. Does it continue after authentication?
