### ISSUE TITLE
Is parcelvoy production ready?

### ISSUE THREAD

**Issue by platform-kit** [parcelvoy/platform#343]
Asking about both the SaaS and the OSS version.

**Comment by pushchris** [comment]
It is currently being used to send millions of messages a day for some users, depends on your needs ultimately!

**Comment by platform-kit** [comment]
Is the api stable, or is it changing frequently?

**Comment by pushchris** [comment]
Yes! The API has been stable since v1.0.0 and every version since has provided automatic migrations for any internal changes.

**Comment by platform-kit** [comment]
Ok, just asking because deploying to render using the one-click button on the readme produces a 502 bad gateway error on deployment. Is the OSS version not regularly maintained?

**Comment by platform-kit** [comment]
Ah I see. Render.com expects a web service to respond to http requests on port 10000 by default. You can specify another port via ENV variable. Do you know what port the app runs on by default? Adding the ENV to `render.yaml` may fix it

**Comment by pushchris** [comment]
The Dockerfile that Render builds exposes everything on port 80

**Comment by platform-kit** [comment]
I see. I tried changing the port to 80, no dice on that front.

Meanwhile I tried to sign up for the SaaS version and was presented with this error:

```
parcelvoy.com has not completed the Google verification process. The app is currently being tested, and can only be accessed by developer-approved testers. If you think you should have access, contact the [developer](https://accounts.google.com/).
```

**Comment by pushchris** [comment]
Thanks for the callout @platform-kit! We are still pending verification, we were told it takes 6+ weeks apparently when we submitted for it. 

Have been trying to get to the bottom of the Render builds, but very unsure what is going on with their platform. There is an updated Dockerfile that correctly builds and attempts to boot after whatever changes they've made. Unfortunately their MySQL instances have an oddity that prevents the MySQL adapter in the project from properly connecting. Originally thought it was something to do with them changing the access of their non-root MySQL users, but root doesn't appear to be working either. Am most likely just going to remove it from the docs at this point and point people towards running it using Docker Compose or some other solution. Feel free however to give the latest a try and let us know if you have any further luck!

**Comment by pushchris** [comment]
@platform-kit the Render blueprint has been fixed. Have successfully deployed it a few times, however you do still have to set the `BASE_URL` parameter since it can't be inferred. The Google auth verification also came through so that error is gone as well.

**Comment by platform-kit** [comment]
@pushchris great work. Just deployed to Render. I appreciate the attention to this, thanks.

I looked into the `BASE_URL` issue and came across this post on Render's support forum:
https://community.render.com/t/reference-service-external-url-in-render-yaml/16110

> You may be able to utilize the envVarKey attribute on your static site declaration, with the `RENDER_EXTERNAL_HOSTNAME` [environment variable 3](https://render.com/docs/environment-variables) e.g.:

```
...
envVars:
  - key: BACKEND_URL
    fromService:
      type: web
      name: backend-service-name
      envVarKey: RENDER_EXTERNAL_HOSTNAME
```

**Comment by pushchris** [comment]
@platform-kit is that an error in the Render logs or on the site when you try and load it? If it's on the site, could you peek at the inspector and see if there are any error messages popping up? If there are any XHR requests in there could also be something to look at. Using the latest render file and setting the `BASE_URL` to be `https://deployment_name.onrender.com` I was able to get everything to boot properly so may still be something there.

**Comment by platform-kit** [comment]
@pushchris  It seems to have resolved itself after an hour. Earlier the error was on the UI side, but the logs showed nothing - just `200`'s.

**Comment by pushchris** [comment]
Definitely found that the first deployment seemed to take a bit to clear out their CDN on my end as well. Going to close this thread for now, please feel free to open another if you run into any further issues! Appreciate all your help debugging.
