### ISSUE TITLE
Gates not using event data

### ISSUE THREAD

**Issue by jordanjoyce** [parcelvoy/platform#344]
Setting up a pretty basic gate check using event data and it never seems to work. Gates are working when I use user values, its just any that use event data don't seem to evaluate. It may be related but I am also unable to set a Data Key value to then entrance, it just never saves. Using the latest docker images.

**Comment by pushchris** [comment]
@jordanjoyce opened a PR that should address the data key issue you are experiencing. Can you give more details about what you are describing relating to gate event filtering? An example would be helpful to be able to try and replicate what you are experiencing

**Comment by pushchris** [comment]
There is a new release v1.1.7 out that should address the data key issue, please let us know if it resolves the problem for you

**Comment by jordanjoyce** [comment]
Created a small reproducable and attached the relevent database rows for you. I've tried several different iterations on this, added a delay before the event to make sure it's not a timing issue and it just seems to not work on any event based conditions. 

<details><summary>journey_steps </summary>
<p>

| id | type | journey\_id | child\_id | data |
| :--- | :--- | :--- | :--- | :--- |
| 34 | entrance | 4 | null | {"trigger": "event", "multiple": false, "concurrent": false, "event\_name": "posted\_job"} |
| 35 | gate | 4 | null | {"rule": {"path": "$", "type": "wrapper", "uuid": "6dc5dbd4-e372-437b-bd62-b0b9b6d7f8ca", "group": "parent", "children": \[{"path": "$.name", "type": "wrapper", "uuid": "a6d950a7-566e-4935-b7b3-e1a3d3e649e3", "group": "event", "value": "posted\_job", "children": \[{"path": "$.category", "type": "string", "uuid": "05fe02d2-0a28-4e36-9060-1b99e7f0d89d", "group": "event", "value": "Cleaners", "operator": "=", "root\_uuid": "6dc5dbd4-e372-437b-bd62-b0b9b6d7f8ca", "parent\_uuid": "a6d950a7-566e-4935-b7b3-e1a3d3e649e3"}\], "operator": "and", "root\_uuid": "6dc5dbd4-e372-437b-bd62-b0b9b6d7f8ca", "parent\_uuid": "6dc5dbd4-e372-437b-bd62-b0b9b6d7f8ca"}\], "operator": "and"}} |
| 36 | action | 4 | null | {"campaign\_id": 19} |
</p>
</details> 
<details><summary>journey_user_steps</summary>
<p>
| id | user\_id | journey\_id | step\_id | type | created\_at | updated\_at | delay\_until | entrance\_id | ended\_at | data | ref |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 586 | 142 | 4 | 34 | completed | 2024-02-06 11:33:32 | 2024-02-06 11:33:32 | null | null | 2024-02-06 11:33:32 | {"event": {"name": "posted\_job", "category": "Cleaners", "created\_at": "2024-02-06T01:33:32.000Z"}} | null |
| 587 | 142 | 4 | 35 | completed | 2024-02-06 11:33:32 | 2024-02-06 11:33:32 | null | 586 | null | null | null |

</p>
</details> 

<details><summary>user_events</summary>
<p>
| id | project\_id | user\_id | data | created\_at | updated\_at |
| :--- | :--- | :--- | :--- | :--- | :--- |
| 477 | 4 | 142 | {"category": "Cleaners"} | 2024-02-06 11:33:32 | 2024-02-06 11:33:32 |



</p>
</details>

**Comment by jordanjoyce** [comment]
> There is a new release v1.1.7 out that should address the data key issue, please let us know if it resolves the problem for you

1.1.7 has fixed the data key issue but not resolved the gate issue

**Comment by pushchris** [comment]
@jordanjoyce ok so the short answer is, technically the `category` parameter is housed inside of a JSON `data` key. In theory it should unwrap this under the hood such that it doesn't matter to the user, but there is an issue somewhere with that step. If you replace `$.category` with `$.data.category` it'll work (but obviously not ideal). Will post once there is a bug fix available for this.

**Comment by jordanjoyce** [comment]
Thanks for the quick reply, that's resolved the issue! Could of sworn I tried that but apparently not 🤦

**Comment by jordanjoyce** [comment]
While talking about events, am I correct in assuming that if I were using a gate system like this I cannot use the event in a campaign template? Or is there a way after some gating and delaying that I could pull the event data in
