### ISSUE TITLE
POST 400 (Bad Request)

### ISSUE THREAD

**Issue by lexciobotariu** [parcelvoy/platform#363]
### Discussed in https://github.com/parcelvoy/platform/discussions/362

<div type='discussions-op-text'>

<sup>Originally posted by **lexciobotariu** February 19, 2024</sup>
Hi there,

I've deployed the platform on render.com set the `BASE_URL` accordingly and set the `CNAME` in the container settings.
I've configured the SMTP with Google as I have a GSuit account.
I've tried with SSL, TLS and with App Password.

I've tried to send a proof email of the template I've created to test it out. 
Unfortunately, I get a notification error `An error occurred with this request. ` and in the console, I get another error saying the following: `POST https://xxxx.xxxx.net/api/admin/projects/1/templates/1/proof 400 (Bad Request)`

What am I missing?

Thank you!
 </div>

**Comment by pushchris** [comment]
Hello! If you set the `LOG_LEVEL` environment variable to `info` does it give you any additional information about what the error might be? You may also need to set `NODE_ENV` to `development` for them to show in logs. Would be curious what the actual message is there.
