### ISSUE TITLE
Email font looks to narrow – how to configure it?

### ISSUE THREAD

**Issue by mattes3** [parcelvoy/platform#372]
The font for the generated emails is Ubuntu with a small line height. How can I change that? Is there a configuration for this?

Example:
<img width="413" alt="CleanShot 2024-03-09 at 16 32 06@2x" src="https://github.com/parcelvoy/platform/assets/2496674/139a4d7e-a682-4c88-bb71-6d62942ad16a">

**Comment by pushchris** [comment]
Line height can be set for each text element, but there is not currently a way to set it globally unfortunately.

<img width="299" alt="Screenshot 2024-03-09 at 12 04 23 PM" src="https://github.com/parcelvoy/platform/assets/679974/be6fba67-08b0-4785-9887-54872256afb5">

**Comment by mattes3** [comment]
I generate mjml code now that contains font attributes on each paragraph, so now it looks good.
