### ISSUE TITLE
I want to migrate from an existing ESP – is there a mass import of campaign templates?

### ISSUE THREAD

**Issue by mattes3** [parcelvoy/platform#373]
Until now, I have been using ConvertKit. I would like to switch to Parcelvoy, but I am afraid of the amount of work to migrate all my email templates.

Is there any automation for that?

**Comment by pushchris** [comment]
Hello @mattes3 how exactly are you using ConverKit currently and in what format are the email templates? Are the templates such that you are re-using them or are they for historical purposes?

**Comment by mattes3** [comment]
Hi @pushchris ,

very good question!

I am using it as a newsletter provider and an email automation tool for onboarding new users of my web applications.

The templates in ConvertKit are more or less HTML, mixed with some proprietary extensions. Some of them are inside an onboarding sequence that I still use. It has daily emails. Some other templates only exist because I still find them interesting, so you were right about the historical purpose!

When I think about it, I realize that I do not really need the GrapesJS editor, but a simple rich text editor would be sufficient. One could then convert the markdown syntax to MJML easily.

Tomorrow I will try to do a fork of Parcelvoy and replace GrapesJS inside VisualEditor.tsx with a simpler editor. Let's see what happens. Maybe the Parcelvoy output will feel more plain newsletter-like afterwards.

If it works, I will send you a link to the fork on GitHub so you can decide to keep it, to make it configurable, or to throw it away entirely. 😎

Cheers,
Matthias

**Comment by mattes3** [comment]
I stopped doing this because it was easier to write a small utility that turns Markdown into mjml code. I just upload the mjml into the Parcelvoy editor and click "Save". Job done.

I converted all my old ConvertKit messages to Markdown (using `npm turndown`), so that I can now use them with Parcelvoy.
