### ISSUE TITLE
Q: when a user clicks on a link in an email, can you trigger a journey on that?

### ISSUE THREAD

**Issue by mattes3** [parcelvoy/platform#382]
I mean, is a link click an event?

**Comment by pushchris** [comment]
Yes! It will trigger a `email_clicked` event that you can then use in journeys. The event contains the campaign name, ID, subscription ID and some related context that you can use for filtering

**Comment by mattes3** [comment]
Is there a way to see a list of previous events for a certain user?

**Comment by pushchris** [comment]
Yes! You can look up the user by ID, email or phone on the users page then navigate to the events tab. Clicking on any event will show you its full payload.

<img width="1046" alt="Screenshot 2024-03-16 at 10 26 27 AM" src="https://github.com/parcelvoy/platform/assets/679974/b297b245-6818-468d-9a8a-305f1f5283c9">
<img width="1686" alt="Screenshot 2024-03-16 at 10 27 47 AM" src="https://github.com/parcelvoy/platform/assets/679974/0b1e31cd-cff2-4eb5-8f51-cd554ae71204">

**Comment by mattes3** [comment]
Ah, this is cool, thank you, Chris!
