### ISSUE TITLE
Self-host - Onboarding Stuck

### ISSUE THREAD

**Issue by tanmay-predisai** [parcelvoy/platform#393]
We installed Parcelvoy on AWS. Once we login we see a "Looks Like You're Lost! The page or resource you are looking for does not exist or has been moved." error. 
When I click on back, it show the base page with the button to "create project". However, it redirects immediately to the same error again. 

The URL stays at http://ec2-ip:3000/organization/projects/onboarding

<img width="811" alt="Screenshot 2024-03-21 at 4 09 15 PM" src="https://github.com/parcelvoy/platform/assets/107187095/30b93dff-820e-4135-9908-1f9a0d505c49">

Is there any configuration that's needed? 

I also tried updating the BASE_URL to the ec2 URL. same status.

**Comment by pushchris** [comment]
That is funky! Will look into why you were redirected there, but see if you can manually navigate to `http://ec2-ip:3000/onboarding` which should have the onboarding steps for ya

**Comment by tanmay-predisai** [comment]
Hello @pushchris, Thank you for the help. This helped. However, now when I am trying to create a project, its showing the following error

<img width="690" alt="Screenshot 2024-03-23 at 9 52 36 AM" src="https://github.com/parcelvoy/platform/assets/107187095/73458014-43d4-4b2a-833f-7dede80d8fe5">

Could you please check if there is any other configuration needed?
