### ISSUE TITLE
Self-Hosting on Ec2 - Onboarding Stuck

### ISSUE THREAD

**Issue by tanmay-predisai** [parcelvoy/platform#399]
Hello @pushchris, Thank you for the help. This helped. However, now when I am trying to create a project, its showing the following error

<img width="690" alt="Screenshot 2024-03-23 at 9 52 36 AM" src="https://github.com/parcelvoy/platform/assets/107187095/73458014-43d4-4b2a-833f-7dede80d8fe5">

Could you please check if there is any other configuration needed?

_Originally posted by @tanmay-predisai in https://github.com/parcelvoy/platform/issues/393#issuecomment-2016341812_

**Comment by pushchris** [comment]
Thanks for reporting this! Looks like it was a regression in 1.3.5, just merged a fix that will be available in the next release. Until then, if you have access to the underlying database you can resolve by finding your admin user and changing their role to `owner`

**Comment by tanmay-predisai** [comment]
Hello @pushchris Thank you for the help. I updated this, restarted docker, and still see the same error. Here is the screenshot of the table with the updated value. Do you think i need to update somewhere else too? 

<img width="1034" alt="Screenshot 2024-03-25 at 12 13 57 PM" src="https://github.com/parcelvoy/platform/assets/107187095/16ebbbe3-6609-49e1-b3b8-9223cc942118">

**Comment by pushchris** [comment]
Unsure at this point, but best guess is maybe your JWT still has your old role in it so you would want to log out and then back in? 1.4.0 is out which has fixes for the errors you described so you could also try doing a fresh install. The admin you listed also doesn't have an organization ID which is very odd to me, are there any items in the `organizations` table?
