### ISSUE TITLE
End journeys early

### ISSUE THREAD

**Issue by jordanjoyce** [parcelvoy/platform#407]
Posted  in discussions but not sure if that is checked. Just a small feature request. 

Would love the ability to end journeys early, on a user by user basis, via either the API or when an event occurs for a user. We have some long running flows, and if we get a conversion in that time frame it would be great to be able to end the journey for the user.

We're currently just doing this via a custom api route, directly deleting from the database, but would be great to have an official API endpoint. 

For an API version would require an endpoint being able to fetch the journeys a user is currently active in, then another to delete them from the journey.

**Comment by pushchris** [comment]
@jordanjoyce appreciate the suggestion, we'll explore how we can incorporate exclusion criteria to allow for exiting a user from a journey based on a rule into the product. For the time being though hopefully #408 gets you part of the way there.

How to use:
- Fetch a users journeys `GET /api/client/users/:externalUserId/journeys` which will return a paginated list of the entrances a user has and the associated journey
- Do some sort of filtering on your side to determine which ones you care about and pull the corresponding IDs
- Remove a user from a journey. You can do this two ways:
  - Remove by the entrance ID (useful if a user can be in a journey multiple times or you have multiple entrances in a journey): `DELETE /api/client/journeys/:journeyId/entrances/:entranceId/users/:externalUserId`
  - Remove all active entrances a user has in a journey: `DELETE /api/client/journeys/:journeyId/users/:externalUserId`

**Comment by pushchris** [comment]
Closing this for now, will ping if we end up adding a UI for setting up rules to exit a journey
