### ISSUE TITLE
Is "created_at" set during upload of a static list?

### ISSUE THREAD

**Issue by mattes3** [parcelvoy/platform#416]
Hi, after uploading a list, I saw that created_at appears in the JSON notation of each user but in the overview of all users, it has today's date in every user. How should this truly work?

It would be nice if the date was the old date from the uploaded file.

**Comment by pushchris** [comment]
I am unable to replicate this one, can you provide any additional details? When uploading users the created at date of the user will be the date at which the user was created. Subsequent uploads of the same list shouldn't change the date since it would be the same user

**Comment by mattes3** [comment]
The list was empty before, in fact the entire database was new. So I expected that each user would have the `created_at` from the row inside the CSV, not the date when the import itself was done.

This is a sample line that I imported:

```
external_id,created_at,email,first_name,last_name,timezone,referrer_url,subscription_url,interested_in_2q2m,interested_in_customerping,interested_in_marketingstuff,interested_in_newsbundler
126490822727749b163d6b3831f030678c6aca22352634a00703094892f85014,2024-03-25T06:02:49.000Z,someone@example.com,"Name","",,,,false,true,false,false
```

Maybe you can test it with this.

**Comment by pushchris** [comment]
Ah! I was misunderstanding what you were saying. You want the created at to come from the file you are importing instead of the date that the user was created in the Parcelvoy database. That should be possible, let me have a look
