### ISSUE TITLE
Searching for users does not work

### ISSUE THREAD

**Issue by mattes3** [parcelvoy/platform#420]
I have a user named "Matthias". When I enter an "a" inside the search box above the list of users, I get the message "No results".

**Comment by pushchris** [comment]
User search is not a fuzzy search by design currently, it only does exact comparison for email, ID and phone. The name field isn't searchable at all as its not an indexed field and only exists inside of a JSON document of properties associated to the user

**Comment by mattes3** [comment]
Could you change the exact equality operator to an ILIKE, at least?

i.e. `WHERE email ILIKE '%substring%'`?

**Comment by pushchris** [comment]
Searching with wildcard operators on both sides unfortunately prevents usage of the table indexes and becomes really inefficient at scale causing locks and other problems. If in the future a search engine is added to the product this might become possible but not as it currently stands
