### ISSUE TITLE
Q: Does Parcelvoy merge user attributes across multiple calls to the /identify API?

### ISSUE THREAD

**Issue by mattes3** [parcelvoy/platform#435]
What happens if I call /identify twice, using the same `external_id` but different `data` attributes for my user? Will they add up in the same user entry in the database? (At least that is what I would expect).

**Comment by pushchris** [comment]
Correct, however it does a soft merge replacing existing values with new ones. Take that into account when passing up objects for example or arrays. Two arrays wont be merged together, the first one will be replaced by the subsequent one
