### ISSUE TITLE
Q: How do I activate a new journey for old users?

### ISSUE THREAD

**Issue by mattes3** [parcelvoy/platform#448]
These questions are about a topic that I had with every email automation system:

1. How do I make sure that users **who sign up** for one of my SaaS products get a certain journey? This is easy to answer: Make the SaaS product fire a `user_signed_up` event and make the journey entrance trigger on that event.
2. **But**: How do I make sure that all users **who signed up in the past** (before the new journey even existed) also get the same journey delivered to them? They have a field in their user profile that indicates they have signed up for a certain product.

Is there a way to do the second one correctly?

**Comment by pushchris** [comment]
Create a list that contains your existing users (could either upload manually or create a dynamic one that adds any users created before a certain date) and then add a second entrance to your journey that adds the users from that list. You can have as many entrances to a journey as you want.

**Comment by mattes3** [comment]
Ah, thank you!

Just for clarification: Do you mean a scheduled entrance so that the system checks daily whether there are any new users that satisfy the criteria? It looks like I could let it run once and then remove the additional entrance when it has added the people to the journey, right? 👇

<img width="926" alt="CleanShot 2024-04-16 at 08 55 20@2x" src="https://github.com/parcelvoy/platform/assets/2496674/b02a2eb3-9b55-4a60-8a56-13925998ca77">

**Comment by pushchris** [comment]
Correct, though definitely confusing given that currently adding from a list is mainly meant for recurring pulls. Just added an additional `Once` frequency to better handle situations like this. Just pick a date to run all of the users in the list through and it'll stop running that entrance after that single first time

**Comment by mattes3** [comment]
Very cool, thank you Chris! 👍

The resulting journey diagram has simplicity and beauty. Let's keep the fingers crossed, the new "schedule once" entrances should trigger tomorrow:

<img width="2064" alt="grafik" src="https://github.com/parcelvoy/platform/assets/2496674/5cb1173e-5d4f-43ee-aaaf-15c539c32649">

**Comment by mattes3** [comment]
"Schedule once" worked. Good!
