### ISSUE TITLE
parcelvoy.com homepage has weird cmd-click behavior in the menu

### ISSUE THREAD

**Issue by mattes3** [parcelvoy/platform#454]
![CleanShot 2024-04-17 at 12 07 17@2x](https://github.com/parcelvoy/platform/assets/2496674/5c5ce76d-e308-43ff-97d5-d11a623ffd78)

When you Cmd-click on one of those links at the top of the parcelvoy.com homepage, you would expect that you stay on the homepage and another tab would open with the content of the linked page.

However, it's the other way round: the current page jumps to the content where the menu item points to, and another tab opens with the current content of the homepage.

Really weird behavior.

Try to Cmd-click some random Google search results to experience the difference.

**Comment by pushchris** [comment]
This is due to the links actually being triggered by some javascript vs being conventional links. Website is in need of a redesign anyways so can revisit when we get around to that
