### ISSUE TITLE
Bug: Can't delete node in Journey builder

### ISSUE THREAD

**Issue by vi1world** [parcelvoy/platform#469]
I'm running Parceyvoy latest version using docker compose.
I can't delete a node in the journey builder when pressing the delete button on the keyboard. Or is there any method for deleting a node?

Thank you

**Comment by pushchris** [comment]
Hey @vi1world I'm unable to reproduce this on my end as described, any chance you could provide some more details? Things that could be helpful:
- What browser and OS you are using
- Minimum reproducible example (video would be great)

Thanks!

**Comment by pushchris** [comment]
Closing this for now as its been a month without any additional details, please feel free to reopen with additional details if you are still experiencing this issue!
