### ISSUE TITLE
Caught errors should be displayed in the STD stream

### ISSUE THREAD

**Issue by reaper** [parcelvoy/platform#476]
Hi,

We only catch errors via the error driver and our sentry instance but not via the containers logs: can you please add errors informations in the STD stream? It would ease the debug.

Thanks a lot.

**Comment by pushchris** [comment]
Getting around to looking into this one, not sure I'm understanding the question. We currently only send errors to Sentry/Bugsnag which it sounds like is what you are using. Container logs contain a full stream of information based on your log level which you can then pipe wherever else you want
