### ISSUE TITLE
Can we auto-update our Parcelvoy AWS EC2 instance with latest release?

### ISSUE THREAD

**Issue by tanmay-predisai** [parcelvoy/platform#482]
Hi, we are restarting our Parcelvoy integration and I realized there are a lot of updates since we tried this the last time.

Would there be a way to set up an auto-update for our AWS EC2 Parcelvoy instance? This can happen periodically or can you please tell us how we can do this manually?

Apologies for the noobish question - not very conversant with the overall setup and trying to read through the docs to figure things out.

**Comment by pushchris** [comment]
To upgrade if you are using Docker Compose you need to shut down the running instances, then pull the latest copy and start the instances backup. Typically looks something like:

```
docker-compose down
docker-compose pull
docker-compose up
```

But it may be different depending on your configuration. If you would like to pin what version you are running, you can do so by setting the version in your environment variables.

If you are just running Docker on a single EC2 there is unfortunately no way to not experience some downtime when performing an upgrade. You would need to look into moving your instance into an autoscaling group of some sort and perform a rolling update where only some instances are ever offline. Elastic Beanstalk, EKS, ECS all allow for this.

**Comment by tanmay-predisai** [comment]
This is helpful. Some downtime is okay for us as of now. We will figure out auto-scaling in the future. Thank you for your help.
