### ISSUE TITLE
Help with setting up OpenID with logto

### ISSUE THREAD

**Issue by Ebaneck** [parcelvoy/platform#487]
Hello,

I am in need of some help with setting up OpenID given that the basic auth setup cannot be extended to support other users out of the box.

I tried setting up parcelvoy with [logto](https://docs.logto.io/docs/recipes/logto-as-idp/) which can act as a standalone identity provider via a [thirdparty application](https://docs.logto.io/docs/recipes/logto-as-idp/configure-3rd-party-app-in-console/) and It seems as though my setup is incorrect.

upon clicking on the parcelvoy login button, the callback url seems to responding with the following error:

```
{
status: "error",
error: "Unable to parse response from OpenID.",
code: 1006
}
```

API server logs:
```
      "response": {
        "status": 204,
        "message": "No Content",
        "header": {
          "vary": "Origin",
          "access-control-allow-origin": "*"
        }
      },
      "app": {
        "subdomainOffset": 2,
        "proxy": true,
        "env": "production"
      },
      "originalUrl": "/api/auth/login/openid/callback",
      "req": "<original node req>",
      "res": "<original node res>",
      "socket": "<original node socket>"
    }
    error: {
      "status": "error",
      "error": "Unable to parse response from OpenID.",
      "code": 1006
    }
```

Parcelvoy env setup:

```
AUTH_DRIVER=openid
AUTH_OPENID_ISSUER_URL=<issuer-url>
AUTH_OPENID_CLIENT_ID=<client-id>
AUTH_OPENID_CLIENT_SECRET=<client-secret>
AUTH_OPENID_REDIRECT_URI=https://<hostname>/auth/login/openid/callback
AUTH_OPENID_DOMAIN_WHITELIST=toto.com
AUTH_OPENID_SCOPES=openid profile email
AUTH_OPENID_NAME=Logto IdP
```

**Comment by Ebaneck** [comment]
Thanks for the pointers @leobarcellos.

While looking throught the network tab, this came up:
```
error: unauthorized_client
error_description: requested response_type is not allowed for this client
```

So I had a closer look at the oidc configurations and I have this setup.

```
"response_modes_supported":["form_post","fragment","query"],"response_types_supported":["code id_token","code","id_token","none"],
```

For a sample request like this, if i switch the response type to `code`, I seem to get a redirect to my consent page.

```
https://5zbknb.logto.app/oidc/auth?client_id=vfponw1y6m3ooh82fpq4l&scope=openid%20email%20profile&response_type=id_token&redirect_uri=https%3A%2F%2Ftoto.mydomain.com%2Fapi%2Fauth%2Flogin%2Fopenid%2Fcallback&response_mode=form_post&nonce=Xp0budfUmr37P3j6TiNg7gs4QVA1fwde3vasUOJSARY&state=https%3A%2F%2Ftoto.mydomain.com%2F
```

Now wondering if we should have both `id_token` and/or `code` in [here](https://github.com/parcelvoy/platform/blob/main/apps/platform/src/auth/OpenIDAuthProvider.ts#L118). ?

**Comment by pushchris** [comment]
The code as it stands isn't setup to accept the `code` response type. Looking at your setup though you support the response type `id_token` so I'm not quite sure why your setup wouldn't just work out of the box.

**Comment by Ebaneck** [comment]
Somehow got it working using the `code` response type with the following changes.

```
diff --git a/apps/platform/src/auth/OpenIDAuthProvider.ts b/apps/platform/src/auth/OpenIDAuthProvider.ts
index 3dd6fe7..c4e860e 100644
--- a/apps/platform/src/auth/OpenIDAuthProvider.ts
+++ b/apps/platform/src/auth/OpenIDAuthProvider.ts
@@ -14,6 +14,7 @@ export interface OpenIDConfig extends AuthTypeConfig {
     clientSecret: string
     redirectUri: string
     domain?: string
+    responseTypes: string[];
 }
 
 export default class OpenIDAuthProvider extends AuthProvider {
@@ -64,6 +65,7 @@ export default class OpenIDAuthProvider extends AuthProvider {
             nonce,
             redirect_uri: this.config.redirectUri,
             state,
+            // responseType: 'code',
         })
 
         ctx.redirect(url)
@@ -115,7 +117,7 @@ export default class OpenIDAuthProvider extends AuthProvider {
             client_id: this.config.clientId,
             client_secret: this.config.clientSecret,
             redirect_uris: [this.config.redirectUri],
-            response_types: ['id_token'],
+            response_types: ['code'],
         })
         return this.client
     }
```

**Comment by pushchris** [comment]
Seems like an easy enough set of changes without sacrificing the original functionality at all (at least if you move the value to come from config). Have opened a PR with the changes

**Comment by Ebaneck** [comment]
Thanks @pushchris. I will give it a try.

**Comment by Ebaneck** [comment]
Hello @pushchris , I can confirm it works as expected.
Just a side note though, we might need to update the docker compose file with the new env.

Thanks again for the quick fix.

**Comment by pushchris** [comment]
Added the value to Docker Compose 👍🏻 thanks for the callout on that!
