### ISSUE TITLE
Template cannot access variable in user object for blast campaigns

### ISSUE THREAD

**Issue by dark-matter08** [parcelvoy/platform#495]
I have an email blast campaign and i have configured the template to load the user's name from the user object as seen
<img width="594" alt="Screenshot 2024-08-28 at 13 26 37" src="https://github.com/user-attachments/assets/cdae6308-39a5-40c1-b7d0-fea16cc866b5">

And when preview the template after loading a user it works fine and good
<img width="1138" alt="Screenshot 2024-08-28 at 13 30 28" src="https://github.com/user-attachments/assets/809cdcd7-8409-4a9c-80ff-a088c0fd87c5">

but when the campaign is sent and received in my email, the name is not loaded
<img width="906" alt="Screenshot 2024-08-28 at 13 30 42" src="https://github.com/user-attachments/assets/ccfbea3d-91ea-48fa-81ba-3846d52aea51">

I also faced the same issue with using webhook on blast campaign, the campaign failed because there user id which was sent in the body object was not received in the api and the following actions all failed

**Comment by pushchris** [comment]
Try {{user.name}}. All properties from the event or user are flattened when processing so they are accessed on one layer. Should make this clearer in the docs and in the preview.

**Comment by dark-matter08** [comment]
my user object does not directly have a `name` property but it does have `full_name`, `first_name` and `last_name`
I tried `{{user.full_name}}` and still has the same issues

**Comment by pushchris** [comment]
Full name is a computed property on the user object that combines first name and last name together. It could be its overriding whatever value you are setting there. For now to see if you can get other any variable to come through, try accessing some other property on the user in the format {{user.property}}

**Comment by pushchris** [comment]
Closing this for now, if you are still having issues please feel free to re-open!
