### ISSUE TITLE
Push notifications not triggering in scheduled journey

### ISSUE THREAD

**Issue by reaper** [parcelvoy/platform#506]
Hi,

I've encountered an issue with a journey scheduled to run daily using a specific user list. Despite the setup, the push notification campaign is never triggered.

To troubleshoot, I replicated the journey to send emails instead of push notifications, and it worked as expected. Additionally, running the campaign manually or sending a proof to a specific user works fine as well.

Could you please advise on how to resolve this issue with the push notifications in the scheduled campaign?

Thank you!

**Comment by reaper** [comment]
Found a path to reproduce: each time you add a block and save, `journey.next_scheduled_at` is set as null.
- create a journey
- add an entrance, daily scheduled with a list, starting from today to the end of week
- save -> next_scheduled_at is null
- add delay, until time 07:00
- save -> next_scheduled_at is null
- update the entrance start date set as tomorrow
- save -> next_scheduled_at is set as tomorrow
- add a send block which triggers a push notification campaign
- save -> next_scheduled_at is null
- update the entrance start date set to a next day
- save -> next_scheduled_at is set

**Comment by pushchris** [comment]
Thanks for reporting! Definitely an issue with how we were evaluating when to change that value. We update all of the steps on save, but if no changes had been made to the schedule that field wouldn't get set which would then cause it to null out. This has been addressed in the latest build, please give it a go and let me know if you run into any additional issues! Thanks!
