### ISSUE TITLE
New Email Provider

### ISSUE THREAD

**Issue by pydubreucq** [parcelvoy/platform#507]
Hi,
I would like to know if you accept new email Provider ? 
I'm the CTO of Sweego (https://www.sweego.io) and I'd like to be able to refer my customers who need automation to Parcelvoy.
Thanks for your response.
Bye

**Comment by pushchris** [comment]
We do! You are welcome to create ones that fit the provider types you offer, just open a PR with the contribution

**Comment by pushchris** [comment]
Closing this for now, please feel free to open a PR with a provider if you get around to it!
