### ISSUE TITLE
Not able to get users to enter journey

### ISSUE THREAD

**Issue by tanmay-predisai** [parcelvoy/platform#512]
Hello, we are trying to implement push notifications with parcelvoy. We have made a journey to send a push-based sequence. We are not able to get users to enter the journey and hence the push notifications are not getting trigerred. 

Here is a screenshot of the input condition to the journey. 
<img width="1425" alt="Screenshot 2024-10-05 at 1 08 23 PM" src="https://github.com/user-attachments/assets/0aaeda9f-57c4-43c0-9a94-42a6011007bf">

Here are the event details of a user - the event seems to be visible under their event list.  
<img width="855" alt="Screenshot 2024-10-05 at 1 10 08 PM" src="https://github.com/user-attachments/assets/2b5bbb97-8eee-44b1-8359-d5a619341d50">

However, this user did not enter the journey. 

ALso, If i make a dynamic list with this configuration, it populates and shows the user in the list
<img width="715" alt="Screenshot 2024-10-05 at 1 09 25 PM" src="https://github.com/user-attachments/assets/d821f8ae-5ce5-4781-926b-ca3a1b2156dc">

How can we debug this further?

**Comment by pushchris** [comment]
Based on that screenshot it is showing seven users have started that entrance step. If you click on the top right checkmark icon it'll show you what the users are in that given step and can be helpful in debugging what step folks are possibly stuck at.

**Comment by tanmay-predisai** [comment]
Apologies for the incomplete information. The 7 users you see were added manually via API to test the journey. 

Once we switched the Entrance to event-based, it has not added any new users. 

My question is - Is the way we have defined the entrance is correct? Is there any sort of debug / logs we can look at to figure out whats being done wrong at our end?

**Comment by pushchris** [comment]
It all looks correct to me, one thing to call out though is that it doesn't retroactively add previous users, its only users from the moment the journey is live moving forward. You can set the console log level to info if you want to get more information about what's going on. One thing I would potentially also try is removing the channel filter to work backwards as to what might not be working for you

**Comment by tanmay-predisai** [comment]
Hello, Is there a possibility that there is a difference between system-generated events and API-generated custom events for Journey Entrance?

1. We have another journey where we add an event for a user via API. The journey entry specifies the same event name, and users get enrolled in the journey and start getting the welcome email sequence. This has been working well for some time now. 
2. The basic difference between the email journey and this new push journey is that the event name "subscribed" is system generated. The register device API is being called here to register the device and that is creating this subscribe event (instead of being sent via API). 
3. The "app list 0.2" that i have shared in the above screenshot is updating properly even now and showing new users being added. However, practically the same conditions being used in Journey Entrance are not working. 


Would you have any thoughts on this?

**Comment by pushchris** [comment]
Just took a peek and you are correct! It looks like subscription events currently are handled slightly differently weren't actually triggering any journey logic, I've just opened a PR that resolves this
