### ISSUE TITLE
Error When Scheduling Campaigns

### ISSUE THREAD

**Issue by Kendarr** [parcelvoy/platform#516]
Hello, 

I am getting an error when Scheduling campaigns for November.

[1728643867551] ERROR (8 on 4323039be22e): error
    ctx: {
      "request": {
        "method": "PATCH",
        "url": "/api/admin/projects/3/campaigns/43",
        "header": {
          "host": "api:3001",
          "connection": "close",
          "content-length": "84",
          "x-forwarded-scheme": "https",
          "x-forwarded-proto": "https",
          "x-forwarded-for": "62.31.56.126, 172.18.0.1",
          "x-real-ip": "172.18.0.1",
          "cf-ray": "8d0e4b0b3fb0bee2-LHR",
          "sec-ch-ua-mobile": "?0",
          "accept-encoding": "gzip, br",
          "priority": "u=1, i",
          "accept-language": "en-GB,en-US;q=0.9,en;q=0.8",
          "referer": "https://parcelvoy.kendalldigital.co.uk/projects/3/campaigns/43",
          "cf-visitor": "{\"scheme\":\"https\"}",
          "cf-ipcountry": "GB",
          "sec-fetch-dest": "empty",
          "sec-fetch-mode": "cors",
          "cdn-loop": "cloudflare; loops=1",
          "sec-fetch-site": "same-origin",
          "cf-connecting-ip": "62.31.56.126",
          "origin": "https://parcelvoy.kendalldigital.co.uk",
          "sec-ch-ua-platform": "\"Windows\"",
          "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
          "accept": "application/json, text/plain, */*",
          "sec-ch-ua": "\"Google Chrome\";v=\"129\", \"Not=A?Brand\";v=\"8\", \"Chromium\";v=\"129\"",
          "content-type": "application/json",

          "cookie": "_ga=GA1.1.1069157331.1728479248; _gcl_au=1.1.1357768196.1728479266; _ga_W3Z6GWM5BE=GS1.1.1728479247.1.1.1728480239.0.0.0; oauth={\"access_token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwib3JnYW5pemF0aW9uX2lkIjoyLCJyb2xlIjoib3duZXIiLCJleHAiOjE3Mjg2NjEyMzAsImlhdCI6MTcyODU3NDgzMH0._CRFh2eccYmhvyOLF21BFEDa--KKWvcRayeoTVMX15w\",\"expires_at\":\"2024-10-11T15:40:30.386Z\"}; oauth.sig=jC53QtadcIRNjQU1QIp-C5kQ2Qw; cf_clearance=nciOkOhQN5bb_HSvnroxJi1HXNp0QYaMGmFC_fKypqg-1728641319-1.2.1.1-Oht56QohXajDhhJYbq1nKs71_BP8FkjvdtkC3zk0O9oj9dYy5HfkFTEwNcUKo70KvWvUTrtL_GrGX3bmDSFl3aYtHCTcfI5bExgJA0ilPszuByc7m99f3gp7edaq6LEiN92AO4v9vH81INHkw.SRJogEQlfUPPidNV4AvDFo.hg9Sw4BTrg941VojOBrVfYfro3B4P9wTYELhuQZDxHuRDe7AYG7M7f0mATU3BxbcwTpaWyc8BUTj8vW1dpRPa92rB1mOOOv1R3z8JVWDl8jxJTPhN0UuNHauh0cdm6CQCIhA1hFhUsrq5Q0ExchdckUNPJtu.FO9.zUlvgdGbg2dfBBd6MCc8UUONhLBpxikxjO1D4Ey_4tXX8vREbzUtCl"
  Error: update `campaigns` set `send_at` = '2024-11-02T09:00:00Z', `send_in_user_timezone` = false, `state` = 'pending', `updated_at` = '2024-10-11 10:51:07.547' where `id` = 43 - Incorrect datetime value: '2024-11-02T09:00:00Z' for column 'send_at' at row 1
        }
      at createQueryBuilder (/usr/src/app/node_modules/knex/lib/knex-builder/make-knex.js:320:26)
      },
      at knex (/usr/src/app/node_modules/knex/lib/knex-builder/make-knex.js:101:12)
      "response": {
      at Campaign.table (/usr/src/app/build/core/Model.js:245:16)
        "status": 404,
      at Campaign.update (/usr/src/app/build/core/Model.js:195:33)
      at updateCampaign (/usr/src/app/build/campaigns/CampaignService.js:148:30)
        "message": "Not Found",
        "header": {
          "vary": "Origin",
          "access-control-allow-origin": "*"
        }
      },
      "app": {
        "subdomainOffset": 2,
        "proxy": true,
        "env": "production"
      },
      "originalUrl": "/api/admin/projects/3/campaigns/43",
      "req": "<original node req>",
      "res": "<original node res>",
      "socket": "<original node socket>"
    }
    error: {
      "code": "ER_TRUNCATED_WRONG_VALUE",
      "errno": 1292,
      "sqlState": "22007",
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /usr/src/app/build/campaigns/CampaignController.js:145:16
      at async checkCampaignId (/usr/src/app/build/campaigns/CampaignController.js:23:12)
      at async serve (/usr/src/app/node_modules/koa-static/index.js:59:5)
      at async cors (/usr/src/app/node_modules/@koa/cors/index.js:109:16)
      at async /usr/src/app/build/api.js:48:17
      "sqlMessage": "Incorrect datetime value: '2024-11-02T09:00:00Z' for column 'send_at' at row 1",
      "sql": "update `campaigns` set `send_at` = '2024-11-02T09:00:00Z', `send_in_user_timezone` = false, `state` = 'pending', `updated_at` = '2024-10-11 10:51:07.547' where `id` = 43",
      "originalStack": "Error: update `campaigns` set `send_at` = '2024-11-02T09:00:00Z', `send_in_user_timezone` = false, `state` = 'pending', `updated_at` = '2024-10-11 10:51:07.547' where `id` = 43 - Incorrect datetime value: '2024-11-02T09:00:00Z' for column 'send_at' at row 1\n    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:738:17)\n    at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:29:26)\n    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:481:34)\n    at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:97:12)\n    at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:104:25)\n    at Socket.emit (node:events:517:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
      "headers": {
        "Access-Control-Allow-Origin": "*",
        "vary": "Origin"
      }
    }

[1728643959306] ERROR (8 on 4323039be22e): error
    ctx: {
      "request": {
        "method": "PATCH",
        "url": "/api/admin/projects/3/campaigns/43",
        "header": {
          "host": "api:3001",
          "connection": "close",
          "content-length": "84",
          "x-forwarded-scheme": "https",
          "x-forwarded-proto": "https",
          "x-forwarded-for": "62.31.56.126, 172.18.0.1",
          "x-real-ip": "172.18.0.1",
          "cf-ray": "8d0e4d48bed794c0-LHR",
          "sec-ch-ua-mobile": "?0",
          "accept-encoding": "gzip, br",
          "priority": "u=1, i",
          "accept-language": "en-GB,en-US;q=0.9,en;q=0.8",
          "referer": "https://parcelvoy.kendalldigital.co.uk/projects/3/campaigns/43",
          "cf-visitor": "{\"scheme\":\"https\"}",
          "cf-ipcountry": "GB",
          "sec-fetch-dest": "empty",
          "sec-fetch-mode": "cors",
          "cdn-loop": "cloudflare; loops=1",
          "sec-fetch-site": "same-origin",
          "cf-connecting-ip": "62.31.56.126",
          "origin": "https://parcelvoy.kendalldigital.co.uk",
          "sec-ch-ua-platform": "\"Windows\"",
          "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
          "accept": "application/json, text/plain, */*",
          "sec-ch-ua": "\"Google Chrome\";v=\"129\", \"Not=A?Brand\";v=\"8\", \"Chromium\";v=\"129\"",
          "content-type": "application/json",
          "cookie": "_ga=GA1.1.1069157331.1728479248; _gcl_au=1.1.1357768196.1728479266; _ga_W3Z6GWM5BE=GS1.1.1728479247.1.1.1728480239.0.0.0; oauth={\"access_token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwib3JnYW5pemF0aW9uX2lkIjoyLCJyb2xlIjoib3duZXIiLCJleHAiOjE3Mjg2NjEyMzAsImlhdCI6MTcyODU3NDgzMH0._CRFh2eccYmhvyOLF21BFEDa--KKWvcRayeoTVMX15w\",\"expires_at\":\"2024-10-11T15:40:30.386Z\"}; oauth.sig=jC53QtadcIRNjQU1QIp-C5kQ2Qw; cf_clearance=nciOkOhQN5bb_HSvnroxJi1HXNp0QYaMGmFC_fKypqg-1728641319-1.2.1.1-Oht56QohXajDhhJYbq1nKs71_BP8FkjvdtkC3zk0O9oj9dYy5HfkFTEwNcUKo70KvWvUTrtL_GrGX3bmDSFl3aYtHCTcfI5bExgJA0ilPszuByc7m99f3gp7edaq6LEiN92AO4v9vH81INHkw.SRJogEQlfUPPidNV4AvDFo.hg9Sw4BTrg941VojOBrVfYfro3B4P9wTYELhuQZDxHuRDe7AYG7M7f0mATU3BxbcwTpaWyc8BUTj8vW1dpRPa92rB1mOOOv1R3z8JVWDl8jxJTPhN0UuNHauh0cdm6CQCIhA1hFhUsrq5Q0ExchdckUNPJtu.FO9.zUlvgdGbg2dfBBd6MCc8UUONhLBpxikxjO1D4Ey_4tXX8vREbzUtCl"
        }
      },
      "response": {

  Error: update `campaigns` set `send_at` = '2024-11-02T09:00:00Z', `send_in_user_timezone` = false, `state` = 'pending', `updated_at` = '2024-10-11 10:52:39.303' where `id` = 43 - Incorrect datetime value: '2024-11-02T09:00:00Z' for column 'send_at' at row 1
      at createQueryBuilder (/usr/src/app/node_modules/knex/lib/knex-builder/make-knex.js:320:26)
      at knex (/usr/src/app/node_modules/knex/lib/knex-builder/make-knex.js:101:12)
      at Campaign.table (/usr/src/app/build/core/Model.js:245:16)
      at Campaign.update (/usr/src/app/build/core/Model.js:195:33)
      at updateCampaign (/usr/src/app/build/campaigns/CampaignService.js:148:30)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /usr/src/app/build/campaigns/CampaignController.js:145:16
      at async checkCampaignId (/usr/src/app/build/campaigns/CampaignController.js:23:12)
      at async serve (/usr/src/app/node_modules/koa-static/index.js:59:5)
      at async cors (/usr/src/app/node_modules/@koa/cors/index.js:109:16)
      at async /usr/src/app/build/api.js:48:17

        "status": 404,
        "message": "Not Found",
        "header": {
          "vary": "Origin",
          "access-control-allow-origin": "*"
        }
      },
      "app": {
        "subdomainOffset": 2,
        "proxy": true,
        "env": "production"
      },
      "originalUrl": "/api/admin/projects/3/campaigns/43",
      "req": "<original node req>",
      "res": "<original node res>",
      "socket": "<original node socket>"
    }
    error: {
      "code": "ER_TRUNCATED_WRONG_VALUE",
      "errno": 1292,
      "sqlState": "22007",
      "sqlMessage": "Incorrect datetime value: '2024-11-02T09:00:00Z' for column 'send_at' at row 1",
      "sql": "update `campaigns` set `send_at` = '2024-11-02T09:00:00Z', `send_in_user_timezone` = false, `state` = 'pending', `updated_at` = '2024-10-11 10:52:39.303' where `id` = 43",
      "originalStack": "Error: update `campaigns` set `send_at` = '2024-11-02T09:00:00Z', `send_in_user_timezone` = false, `state` = 'pending', `updated_at` = '2024-10-11 10:52:39.303' where `id` = 43 - Incorrect datetime value: '2024-11-02T09:00:00Z' for column 'send_at' at row 1\n    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:738:17)\n    at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:29:26)\n    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:481:34)\n    at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:97:12)\n    at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:104:25)\n    at Socket.emit (node:events:517:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
      "headers": {
        "Access-Control-Allow-Origin": "*",
        "vary": "Origin"
      }
    }

**Comment by pushchris** [comment]
Does schedule for any other time work? What version of MySQL are you running? Can you get a dump of your table schema for the campaigns table? The query itself looks fine to me

**Comment by Kendarr** [comment]
Hi Chris,

Thank you for your reply. I will get this over to you ASAP. Sorry for the delay.

Thank you.

**Comment by Kendarr** [comment]
I am running version mysql:8.0.36

```
mysql> describe campaigns;
+-----------------------+--------------+------+-----+-------------------+-------------------+
| Field                 | Type         | Null | Key | Default           | Extra             |
+-----------------------+--------------+------+-----+-------------------+-------------------+
| id                    | int unsigned | NO   | PRI | NULL              | auto_increment    |
| type                  | varchar(255) | YES  |     | NULL              |                   |
| project_id            | int unsigned | NO   | MUL | NULL              |                   |
| list_ids              | json         | YES  |     | NULL              |                   |
| exclusion_list_ids    | json         | YES  |     | NULL              |                   |
| name                  | varchar(255) | YES  |     |                   |                   |
| channel               | varchar(255) | NO   |     | NULL              |                   |
| provider_id           | int unsigned | NO   | MUL | NULL              |                   |
| subscription_id       | int unsigned | NO   | MUL | NULL              |                   |
| state                 | varchar(20)  | YES  |     | NULL              |                   |
| delivery              | json         | YES  |     | NULL              |                   |
| send_at               | timestamp    | YES  |     | NULL              |                   |
| send_in_user_timezone | tinyint(1)   | YES  |     | 0                 |                   |
| created_at            | timestamp    | YES  |     | CURRENT_TIMESTAMP | DEFAULT_GENERATED |
| updated_at            | timestamp    | YES  |     | CURRENT_TIMESTAMP | DEFAULT_GENERATED |
| deleted_at            | timestamp    | YES  |     | NULL              |                   |
+-----------------------+--------------+------+-----+-------------------+-------------------+
16 rows in set (0.01 sec)

```

**Comment by Kendarr** [comment]
Does schedule for any other time work?

Yes it does! Also if i just send now it works aswell.

**Comment by pushchris** [comment]
Is it only November 2nd that doesn't work? Everything table wise looks fine but wondering if it maybe has something to do with daylight savings (even though that shouldn't affect UTC)

**Comment by pushchris** [comment]
Unsure if this will address or not, but looking again at your values it looks like your browser isn't formatting the date in proper ISO 8601 for some reason so added an extra JS date wrapping once it gets to the backend. https://github.com/parcelvoy/platform/pull/528 (in latest version 1.10.2)

**Comment by Kendarr** [comment]
Hi Chris,

I was using Chrome.

After updating the docker images this is now running perfectly. 

Thank you for your help!
