### ISSUE TITLE
Enhancement Request - User Segmentation

### ISSUE THREAD

**Issue by tanmay-predisai** [parcelvoy/platform#535]
Hello!

The idea is to create a dynamic list with the following conditions - 
1. All users created in the last 2 months. OR
2. All users who have opened emails in the last 3 months. 

This will ensure that the pool of users who receive the weekly newsletters remains fresh - the open rates, etc., are always in good shape. 

I tried creating this Dynamic list:
<img width="791" alt="Screenshot 2024-11-05 at 1 02 52 PM" src="https://github.com/user-attachments/assets/62328bf5-8a05-4815-9f02-031b4b0263b7">
1. The created date as of now can be fixed. Could we have an option like "before y months / before x days"  
2. The email open event can be linked to a specific campaign. Can it be tracked at an overall level - eg. Email opened in last x months. 

Request you to please see if this fits into your roadmap.

**Comment by williamhrs** [comment]
I commented the need for something like that here: https://github.com/parcelvoy/platform/discussions/514#discussioncomment-10974319

**Comment by pushchris** [comment]
This functionality will be available in the next release, please see #538 for details about the implementation

**Comment by tanmay-predisai** [comment]
Hi @pushchris Thank you for working on this. Just curious - when can we expect the new release to be available?
