### ISSUE TITLE
Migration error on fresh local start

### ISSUE THREAD

**Issue by leobarcellos** [parcelvoy/platform#539]
Everytime I make a fresh start (clean mysql), I receive this error from migrations:
`Failed to add the foreign key constraint. Missing unique key for constraint 'rules_root_uuid_foreign' in the referenced table 'rules'`

![Screenshot 2024-11-11 at 1 02 28 PM](https://github.com/user-attachments/assets/3378d55b-5428-45d7-a2b1-ba926a06b3b1)
![Screenshot 2024-11-11 at 1 04 53 PM](https://github.com/user-attachments/assets/a9683fca-7d22-4f3f-8135-95bda0bb9a42)

Not sure why. It's not a big deal since I can manually fix directly on database, but I think it should be fixed (or maybe I'm missing something, I don't  know)

**Comment by pushchris** [comment]
What version of MySQL are you running? Have not been able to reproduce this one

**Comment by leobarcellos** [comment]
@pushchris Hmmm, weird.

Maybe it's specific on this 8.0.39 on mac/arm64?
`mysql  Ver 8.0.39 for macos14.4 on arm64 (Homebrew)`

I will try with again with the Docker version

**Comment by leobarcellos** [comment]
Yes, confirmed. It works with the dockerized MySQL. I'm closing it.
