### ISSUE TITLE
API endpoint to remove users

### ISSUE THREAD

**Issue by Un-dev** [parcelvoy/platform#545]
Would it be relevant/possible to have a client api endpoint to delete users ?

**Comment by pushchris** [comment]
No, the client API utilizes a public facing API key and is not intended for any destructive actions, only for ingestion of data. If you need to manipulate data there are some endpoints available on the admin API (which unfortunately is not super well documented). For removing users, the details of this PR might be helpful: https://github.com/parcelvoy/platform/issues/315

**Comment by Un-dev** [comment]
@pushchris thanks for the fast answer, unfortunately I'm a bit confused, in this discussion you're telling about `DELETE /api/admin/projects/{PROJECT_ID}/users/{ID_TO_DELETE}` and `DELETE /api/admin/projects/{PROJECT_ID}/users?user_id={EXTERNAL_ID}` but none of them are working for me

**Comment by pushchris** [comment]
Are you using a secret API key with admin access? A client key does not work. That first endpoint is used in the UI itself when you delete a user so if thats working for you, then the endpoint is working and it's most likely your key

**Comment by Un-dev** [comment]
My bad, I misread the line, it actually works

thanks for the help !
