### ISSUE TITLE
Question : How to check if user has opened my campaign ?

### ISSUE THREAD

**Issue by Un-dev** [parcelvoy/platform#547]
Suppose I have this schema : 

<img width="1262" alt="Capture d’écran 2024-11-27 à 16 17 52" src="https://github.com/user-attachments/assets/a16497f4-6644-4ae0-ba68-5bf433e502e8">
<br/><br/>
After sending a notification I want to wait 24 hours then check if the user has opened it and if the notification has been sent less than twice, then either redirect him back at the beginning of the journey or get him out of the journey
<br/><br/>
What would be the syntax of the gate block conditions ?

**Comment by williamhrs** [comment]
you can use the event email_opened using something like this ->

![image](https://github.com/user-attachments/assets/5eb2155f-5edc-4dd5-a759-dc325431ac89)

**Comment by pushchris** [comment]
Correct, use properties of the `email_opened` , `push_opened` or `text_opened`
