### ISSUE TITLE
List population issue

### ISSUE THREAD

**Issue by tanmay-predisai** [parcelvoy/platform#573]
Hi! Thank you for the new release :) 
We updated our instance and tested it by creating a new dynamic list. 

I already have a user with the following data
<img width="909" alt="Screenshot 2024-12-10 at 4 50 30 PM" src="https://github.com/user-attachments/assets/6915ffa1-a1cc-4e84-b818-b1274e897646">

I tried creating a dynamic list with the below parameters: (we double checked the value of external id pasted in the box)
<img width="873" alt="Screenshot 2024-12-10 at 4 52 24 PM" src="https://github.com/user-attachments/assets/3208cea0-51b6-4e51-bb57-2f5854c25cf6">

For some reason, the user is not getting added to the list. I also tried with a contains - and the list did not populate.
<img width="713" alt="Screenshot 2024-12-10 at 4 53 13 PM" src="https://github.com/user-attachments/assets/12ea66d0-8e94-41fd-bf7e-74f31745c4ff">

Is there anything we are doing wrong? Any help is appreciated!

**Comment by pushchris** [comment]
So this is an interesting one, technically under the hood we expose `external_id` as `id` for rule matching, but in hindsight I'm not entirely sure that makes sense
