### ISSUE TITLE
Campaign stats not updating

### ISSUE THREAD

**Issue by tanmay-predisai** [parcelvoy/platform#591]
Hello! We sent a campaign to a dynamic list. The campaign stats have stopped updating after a while. 

If I check MySQL for the campaign opens, this is what I see - 
<img width="643" alt="Screenshot 2024-12-27 at 9 58 07 AM" src="https://github.com/user-attachments/assets/dd62a2a3-ea38-46f2-b07b-a93e1cc82b3f" />

ParcelVoy campaign list view shows this 
<img width="172" alt="Screenshot 2024-12-27 at 9 58 20 AM" src="https://github.com/user-attachments/assets/87986400-69e8-400b-8c86-0e1063b9fe2a" />

I see some deadlocks in the performance tab; however, I'm not sure if they are related. 
<img width="1070" alt="Screenshot 2024-12-27 at 10 00 18 AM" src="https://github.com/user-attachments/assets/20e7ee61-ae39-462f-8a51-625530c5b894" />

Am I  looking at this correctly? Would you have any thoughts on how to investigate this?

Another question - My dynamic list's criteria is email opened on or before a certain date. Would this impact the list population as well and we might miss out on some users who have opened the email later but won't be included in the list?

**Comment by pushchris** [comment]
What is "a while"? When did you send the campaign?

**Comment by tanmay-predisai** [comment]
Apologies for missing this - the campaign was sent on 21st December (Friday). The stats updated for 2 days and then stopped. Maybe the dynamic list got regenerated and this update stopped?

**Comment by pushchris** [comment]
That is currently as designed. Campaign stats only update for 48hrs after finishing. Counting queries are expensive and you'd have a thundering horde problem with campaigns continuing to update as you added more and more campaigns with diminishing returns as to what updating the stats would bring you. Could potentially extend slightly, but there will always be a cutoff date where stats stop updating.

**Comment by tanmay-predisai** [comment]
Understood. 

Another question - Our dynamic list's criteria is email opened on or before a certain date. I hope the list population will work as is and we won't miss out on some users who have opened the email after 48 hours?

**Comment by pushchris** [comment]
Rules in lists are based on events and have nothing to do with the campaigns themselves, yes they will continue to update
